/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.io.File;
import java.net.URL;
import java.sql.SQLException;
import java.util.Arrays;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.Mixer;

/**
 *
 * @author Rocio
 */
public class Calculadora extends javax.swing.JFrame {

    double num1;
    double num2;
    double result;
    String respu;
    String operacion;
    private Object math;
    boolean modoOscuro = false;

    public void setTable() {
        PreparedStatement consul = null; 
        ResultSet resultados = null; 
        ResultSetMetaData infobd = null; 
        try {
            DefaultTableModel modelo = new DefaultTableModel(); 
            tabla.setModel(modelo);
            modelo.addColumn("operacion");
            modelo.addColumn("resultado"); 
            com.mysql.jdbc.Connection sql = new conexion().getConexion();
            consul = (PreparedStatement) sql.prepareStatement("SELECT * FROM operaciones");
            resultados = consul.executeQuery();
            infobd = consul.getMetaData();
            int column = infobd.getColumnCount(); 
            Object filas[] = new Object[column]; 
            while (resultados.next()) {
                for (int i = 0; i < column; i++) {
                    filas[i] = resultados.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null, "Hubo un error:" + "Revisar conexión a la BD o a la tabla", "Error", 0, 0);

        }
    }

    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
        setTable();
        playSound(); 
    }
    
    public void playSound() {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/Media/calm_background_music.wav").getAbsoluteFile());
            Mixer.Info[] mixers =  AudioSystem.getMixerInfo(); //declaramos opciones de mixer, depende del tipo de salida
            Clip clip = AudioSystem.getClip(); //este es el mixer de mis auriculares, los tres primeros son de la placa
            //probablemente se deba de cambiar de mixer para poder verse
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            System.out.println("Error al reproducir el sonido");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        div = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        modon = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        historial = new javax.swing.JLabel();
        raiz = new javax.swing.JButton();
        exp2 = new javax.swing.JButton();
        exp3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        dos.setBackground(new java.awt.Color(248, 248, 248));
        dos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dos.setText("2");
        dos.setBorder(null);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(248, 248, 248));
        tres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tres.setText("3");
        tres.setBorder(null);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(77, 218, 218));
        borrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("c");
        borrar.setBorder(null);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(242, 242, 242));
        div.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        div.setText("/");
        div.setBorder(null);
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(248, 248, 248));
        cuatro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cuatro.setText("4");
        cuatro.setBorder(null);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        mult.setBackground(new java.awt.Color(242, 242, 242));
        mult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mult.setText("*");
        mult.setBorder(null);
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(248, 248, 248));
        cinco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cinco.setText("5");
        cinco.setBorder(null);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        pantalla.setBackground(new java.awt.Color(242, 242, 242));
        pantalla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setBorder(null);
        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });
        pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pantallaKeyTyped(evt);
            }
        });

        modon.setBackground(new java.awt.Color(242, 242, 242));
        modon.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        modon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/mododia.jpg"))); // NOI18N
        modon.setBorder(null);
        modon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modonActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(248, 248, 248));
        seis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seis.setText("6");
        seis.setBorder(null);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(248, 248, 248));
        ocho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ocho.setText("8");
        ocho.setBorder(null);
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        resta.setBackground(new java.awt.Color(242, 242, 242));
        resta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resta.setText("-");
        resta.setBorder(null);
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(248, 248, 248));
        nueve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nueve.setText("9");
        nueve.setBorder(null);
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(248, 248, 248));
        cero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cero.setText("0");
        cero.setBorder(null);
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        siete.setBackground(new java.awt.Color(248, 248, 248));
        siete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        siete.setText("7");
        siete.setBorder(null);
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(248, 248, 248));
        punto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        punto.setText(".");
        punto.setBorder(null);
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        suma.setBackground(new java.awt.Color(242, 242, 242));
        suma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        suma.setText("+");
        suma.setBorder(null);
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        uno.setBackground(new java.awt.Color(248, 248, 248));
        uno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uno.setText("1");
        uno.setBorder(null);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(77, 218, 218));
        igual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setBorder(null);
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(242, 242, 242));
        tabla.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Operación", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        historial.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        historial.setText("Historial");

        raiz.setBackground(new java.awt.Color(242, 242, 242));
        raiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raiz.setText("√");
        raiz.setBorder(null);
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });

        exp2.setBackground(new java.awt.Color(242, 242, 242));
        exp2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exp2.setText("x²");
        exp2.setBorder(null);
        exp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp2ActionPerformed(evt);
            }
        });

        exp3.setBackground(new java.awt.Color(242, 242, 242));
        exp3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exp3.setText("x³");
        exp3.setBorder(null);
        exp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exp3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exp2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(historial)
                        .addGap(69, 69, 69)
                        .addComponent(modon)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(exp3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(exp2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        String iNum = pantalla.getText() + nueve.getText();
        pantalla.setText(iNum);
    }//GEN-LAST:event_nueveActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        String iNum = pantalla.getText() + siete.getText();
        pantalla.setText(iNum);
    }//GEN-LAST:event_sieteActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        verif();
        num1 = Double.parseDouble(pantalla.getText());
        pantalla.setText(null);
        operacion = ("+");
    }//GEN-LAST:event_sumaActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        String numero = pantalla.getText() + uno.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_unoActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        String numero = pantalla.getText() + tres.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_tresActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        verif();
        num1 = Double.parseDouble(pantalla.getText());
        pantalla.setText(null);
        operacion = ("/");
    }//GEN-LAST:event_divActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        String numero = pantalla.getText() + cuatro.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_cuatroActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        String numero = pantalla.getText() + seis.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_seisActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        verif();
        num1 = Double.parseDouble(pantalla.getText());
        pantalla.setText(null);
        operacion = ("-");
    }//GEN-LAST:event_restaActionPerformed
    public void verif(){
        if(pantalla.getText().isEmpty()){
            JOptionPane.showConfirmDialog(null, "Ingrese un Valor");
        }
    }
    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        String numero = pantalla.getText() + cero.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_ceroActionPerformed
    public void guardarDatos(String calculo, String Resultado) {
        try {
            java.sql.Connection sql = new conexion().getConexion();
            PreparedStatement pr = null;
            ResultSet rs = null;
            pr = (PreparedStatement) sql.prepareStatement("INSERT INTO operaciones VALUES(?, ?)");
            pr.setString(1, calculo);
            pr.setString(2, Resultado);
            pr.execute();
            setTable();
        } catch (SQLException e) {
            System.err.println(e.toString());
        }
    }
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        String respu;
        verif();
        num2 = Double.parseDouble(pantalla.getText());
        try {
                if (operacion == "+") {
                    result = num1 + num2;
                    respu = String.format("%.2f", result);
                    pantalla.setText(respu);
                    guardarDatos(String.valueOf(num1) + "+" + String.valueOf(num2), respu);
                } else if (operacion == "-") {
                    result = num1 - num2;
                    respu = String.format("%.2f", result);
                    pantalla.setText(respu);
                    guardarDatos(String.valueOf(num1) + "-" + String.valueOf(num2), respu);
                } else if (operacion == "*") {
                    result = num1 * num2;
                    respu = String.format("%.2f", result);
                    pantalla.setText(respu);
                    guardarDatos(String.valueOf(num1) + "*" + String.valueOf(num2), respu);
                } else if (operacion == "/") {
                    result = num1 / num2;
                    respu = String.format("%.2f", result);
                    pantalla.setText(respu);
                    guardarDatos(String.valueOf(num1) + "/" + String.valueOf(num2), respu);
                }
        }
        catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Hubo un error en la operación" + e);
        }


    }//GEN-LAST:event_igualActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        verif();
        num1 = Double.parseDouble(pantalla.getText());
        pantalla.setText(null);
        operacion = ("*");
    }//GEN-LAST:event_multActionPerformed

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        String numero = pantalla.getText() + ocho.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_ochoActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        String numero = pantalla.getText() + cinco.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_cincoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        String numero = pantalla.getText() + dos.getText();
        pantalla.setText(numero);
    }//GEN-LAST:event_dosActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

        pantalla.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        if (!pantalla.getText().contains(".")) {
            pantalla.setText(pantalla.getText() + punto.getText());
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void pantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pantallaKeyTyped

    }//GEN-LAST:event_pantallaKeyTyped

    private void modonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modonActionPerformed
        // TODO add your handling code here:
        if (!modoOscuro) {
            modon.setBackground(Color.decode("#995e06"));
            pantalla.setBackground(Color.decode("#C5C9C6"));
            jPanel1.setBackground(Color.decode("#363636"));
            tabla.setBackground(Color.decode("#b3b3b3"));
            historial.setForeground(Color.decode("#ffffff"));
            uno.setBackground(Color.decode("#C5C9C6"));
            dos.setBackground(Color.decode("#C5C9C6"));
            tres.setBackground(Color.decode("#C5C9C6"));
            cuatro.setBackground(Color.decode("#C5C9C6"));
            cinco.setBackground(Color.decode("#C5C9C6"));
            seis.setBackground(Color.decode("#C5C9C6"));
            siete.setBackground(Color.decode("#C5C9C6"));
            ocho.setBackground(Color.decode("#C5C9C6"));
            nueve.setBackground(Color.decode("#C5C9C6"));
            cero.setBackground(Color.decode("#C5C9C6"));
            punto.setBackground(Color.decode("#C5C9C6"));
            igual.setBackground(Color.decode("#1c947c"));
            resta.setBackground(Color.decode("#9fa19f"));
            mult.setBackground(Color.decode("#9fa19f"));
            div.setBackground(Color.decode("#9fa19f"));
            suma.setBackground(Color.decode("#9fa19f"));
            exp2.setBackground(Color.decode("#9fa19f"));
            exp3.setBackground(Color.decode("#9fa19f"));
            raiz.setBackground(Color.decode("#9fa19f"));
            borrar.setBackground(Color.decode("#1c947c"));
            jPanel1.setForeground(Color.white);
            modon.setIcon(new ImageIcon(getClass().getResource("/Imgs/modonoche.jpg")));
            modoOscuro = true;
        } else {
            Calculadora frame = new Calculadora();
            this.dispose();
            frame.setVisible(true);
        }

    }//GEN-LAST:event_modonActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        // TODO add your handling code here:
        verif();
        double ope = Double.parseDouble(String.valueOf(pantalla.getText()));
        ope = Math.sqrt(ope);
        pantalla.setText(String.valueOf(ope));
    }//GEN-LAST:event_raizActionPerformed

    private void exp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp2ActionPerformed
        // TODO add your handling code here:
        verif();
        double ope = Double.parseDouble(String.valueOf(pantalla.getText()));
        ope = (ope * ope);
        pantalla.setText(String.valueOf(ope));
    }//GEN-LAST:event_exp2ActionPerformed

    private void exp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp3ActionPerformed
        // TODO add your handling code here:
        verif();
        double ope = Double.parseDouble(String.valueOf(pantalla.getText()));
        ope = (ope * ope * ope);
        pantalla.setText(String.valueOf(ope));
    }//GEN-LAST:event_exp3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton div;
    private javax.swing.JButton dos;
    private javax.swing.JButton exp2;
    private javax.swing.JButton exp3;
    private javax.swing.JLabel historial;
    private javax.swing.JButton igual;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modon;
    private javax.swing.JButton mult;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JTextField pantalla;
    private javax.swing.JButton punto;
    private javax.swing.JButton raiz;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JTable tabla;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables

}
